### ISSUE TITLE
Need to fix inline comment

### ISSUE THREAD

**Issue by erguotou520** [apigee/yaml2#1]

**Comment by mohsen1** [comment]
please provide input and desired output

**Comment by erguotou520** [comment]
Input:
```yaml
foo: 123 # this is foo
bar: 456 # this is bar
```
Output:
```yaml
-
  key: foo
  value: 123
  comment: this is foo
-
  key: bar
  value: 456
  comment: this is bar
```
